[chore] added User-Agent to api calls

diff --git a/ani-skip-jq b/ani-skip-jq
--- a/ani-skip-jq
+++ b/ani-skip-jq
@@ -1,12 +1,14 @@
 #!/bin/sh
 
+agent="Mozilla/5.0 (Windows NT 6.1; Win64; rv:109.0) Gecko/20100101 Firefox/109.0"
+
 die() {
     printf "\33[2K\r\033[1;31m%s\033[0m\n" "$*" >&2
     exit 1
 }
 
 update_script() {
-    update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/synacktraa/ani-skip/master/ani-skip")" || die "Connection error"
+    update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/synacktraa/ani-skip/master/ani-skip-jq")" || die "Connection error"
     update="$(printf '%s\n' "$update" | diff -u "$0" -)"
     if [ -z "$update" ]; then
         printf "Script is up to date :)\n"
@@ -26,10 +28,10 @@ get_skip_times() {
 
         name=$(printf "%s" "$title" | sed -E "s@(.+\b)( \().*@\1@")
         keyword=$(printf "%s" "$name" | sed -E 's| |%20|g')
-        mal_id=$(curl -s "https://myanimelist.net/search/prefix.json?type=anime&keyword=$keyword" | jq .categories[].items[0].id)
+        mal_id=$(curl -s -A "$agent" "https://myanimelist.net/search/prefix.json?type=anime&keyword=$keyword" | jq .categories[].items[0].id)
         [ -z "$mal_id" ] && printf "\033[1;31mMyAnimeList ID not found!\033[0m\n" 1>&2 && return 1
 
-        aniskip_output=$(curl -s "https://api.aniskip.com/v1/skip-times/$mal_id/$ep_no?types[]=op")
+        aniskip_output=$(curl -s -A "$agent" "https://api.aniskip.com/v1/skip-times/$mal_id/$ep_no?types[]=op")
         found_status=$(printf "%s" "$aniskip_output" | jq .found)
         [ "$found_status" = "false" ] && printf "\033[1;31mSkip times not found!\033[0m\n" 1>&2 && return 1
         
