[chore] Condensed code into a single function

diff --git a/ani-skip b/ani-skip
--- a/ani-skip
+++ b/ani-skip
@@ -1,28 +1,21 @@
 #!/bin/sh
 
-get_MAL_Id() {
+get_skip_times() {
+        name=$(printf "%s" "$title" | sed -E "s@(.+\b)( \().*@\1@")
+        keyword=$(printf "%s" "$name" | sed -E 's| |%20|g')
+        mal_output=$(curl -s "https://myanimelist.net/search/prefix.json?type=anime&keyword=$keyword")
+        mal_id=$(printf "%s\n" "$mal_output" | grep -Eo '"id"[^}]+'| sed -E 's@"id":([0-9]{1,}),.+name":"([^"]+).+@\2|\1@g'| grep -Eo "^$name\|.*" | sed -E "s@.+\|(.+)@\1@")
+        [ -z "$mal_id" ] && printf "\033[1;31mMyAnimeList ID not found!\033[0m\n" && return 1
 
-        name=$(printf "%s" "$*"| sed -E "s!(.+\b)( \().*!\1!")
-        key=$(printf "%s" "$name"| sed -E 's| |%20|g')
-        json=$(curl -s $(printf "https://myanimelist.net/search/prefix.json?type=anime&keyword=%s" "$key"))
-        MAL_ID=$(printf "%s\n" "$json" | grep -Eo '"id"[^}]+'| sed -E 's!"id":([0-9]{1,}),.+name":"([^"]+).+!\2|\1!g'|\
-                 grep -Eo "^$name\|.*" | sed -E "s!.+\|(.+)!\1!")
+        aniskip_output=$(curl -s "https://api.aniskip.com/v1/skip-times/$mal_id/$ep_no?types[]=op")
+        found_status=$(printf "%s" "$aniskip_output" | sed -E 's_\{"found":(true|false),.*_\1_p' | head -n1)
+        [ "$found_status" = "false" ] && printf "\033[1;31mSkip times not found!\033[0m\n" && return 1
 
+        opts_flag=$(printf "%s" "$aniskip_output" | sed -E 's@.*"([a-z_]+)":([0-9.]+),"([a-z_]+)":([0-9.]+).*:"op".*@--script-opts=skip-\1=\2,skip-\3=\4@')
+        skip_flag="$opts_flag --script=~/.config/mpv/scripts/skip.lua"
 }
 
-genopts() {
+[ "$#" -ne 2 ] && printf "%s [\"title\"] [ep]\n" "${0##*/}" && exit 1
 
-        res=$(curl -s $(printf "https://api.aniskip.com/v1/skip-times/%s/%s?types[]=op" $MAL_ID $1))
-        status=$(printf "%s" "$res" |sed -E 's_\{"found":(true|false),.*_\1_p' | head -n1)
-        [ "$status" = "true" ] && printf "%s" "$res" | \
-                sed -E 's!.*"([a-z_]+)":([0-9.]+),"([a-z_]+)":([0-9.]+).*:"op".*!--script-opts=skip-\1=\2,skip-\3=\4!'
-}
-
-[ -z "$*" ] && printf "%s [\"title\"] [ep]\n" "${0##*/}" && exit 1
-
-title="$1"
-ep_no="$2"
-
-get_MAL_Id "$title"
-genopts $ep_no 
-
+title="$1" ep_no="$2" get_skip_times
+echo $skip_flag
