[chore] yoinked die and update_script from ni-cli repo

diff --git a/ani-skip b/ani-skip
--- a/ani-skip
+++ b/ani-skip
@@ -1,24 +1,45 @@
 #!/bin/sh
 
+die() {
+    printf "\33[2K\r\033[1;31m%s\033[0m\n" "$*" >&2
+    exit 1
+}
+
+update_script() {
+    update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/synacktraa/ani-skip/master/ani-skip")" || die "Connection error"
+    update="$(printf '%s\n' "$update" | diff -u "$0" -)"
+    if [ -z "$update" ]; then
+        printf "Script is up to date :)\n"
+    else
+        if printf '%s\n' "$update" | patch "$0" -; then
+            printf "Script has been updated\n"
+        else
+            die "Can't update for some reason!"
+        fi
+    fi
+    exit 0
+}
+
 get_skip_times() {
         lua_script="$HOME/.config/mpv/scripts/skip.lua"
-        [ ! -f "$lua_script" ] && printf "\033[1;31m'skip.lua' script not found!\033[0m\n" 1>&2 && return 1
+        [ ! -f "$lua_script" ] && die "'skip.lua' script not found!"
         
         name=$(printf "%s" "$title" | sed -E "s@(.+\b)( \().*@\1@")
         keyword=$(printf "%s" "$name" | sed -E 's| |%20|g')
         mal_output=$(curl -s "https://myanimelist.net/search/prefix.json?type=anime&keyword=$keyword")
         mal_id=$(printf "%s\n" "$mal_output" | grep -Eo '"id"[^}]+'| sed -E 's@"id":([0-9]{1,}),.+name":"([^"]+).+@\2|\1@g'| grep -Eo "^$name\|.*" | sed -E "s@.+\|(.+)@\1@")
-        [ -z "$mal_id" ] && printf "\033[1;31mMyAnimeList ID not found!\033[0m\n" 1>&2 && return 1
+        [ -z "$mal_id" ] && die "MyAnimeList ID not found!"
 
         aniskip_output=$(curl -s "https://api.aniskip.com/v1/skip-times/$mal_id/$ep_no?types[]=op")
         found_status=$(printf "%s" "$aniskip_output" | sed -E 's_\{"found":(true|false),.*_\1_p' | head -n1)
-        [ "$found_status" = "false" ] && printf "\033[1;31mSkip times not found!\033[0m\n" 1>&2 && return 1
+        [ "$found_status" = "false" ] && printf "Skip times not found!"
 
         options=$(printf "%s" "$aniskip_output" | sed -E 's@.*"([a-z_]+)":([0-9.]+),"([a-z_]+)":([0-9.]+).*:"op".*@skip-\1=\2,skip-\3=\4@')
         skip_flag="--script-opts=$options --script=$lua_script"
 }
 
-[ "$#" -ne 2 ] && printf "%s [\"title\"] [ep]\n" "${0##*/}" && exit 1
+[ "$#" -eq 1 ] && [ "$1" = "-U" ] && update_script
+[ "$#" -ne 2 ] && die "${0##*/} [\"title\"] [ep]"
 
 title="$1" ep_no="$2" get_skip_times
 printf "%s" "$skip_flag"
diff --git a/ani-skip-jq b/ani-skip-jq
--- a/ani-skip-jq
+++ b/ani-skip-jq
@@ -1,5 +1,25 @@
 #!/bin/sh
 
+die() {
+    printf "\33[2K\r\033[1;31m%s\033[0m\n" "$*" >&2
+    exit 1
+}
+
+update_script() {
+    update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/synacktraa/ani-skip/master/ani-skip")" || die "Connection error"
+    update="$(printf '%s\n' "$update" | diff -u "$0" -)"
+    if [ -z "$update" ]; then
+        printf "Script is up to date :)\n"
+    else
+        if printf '%s\n' "$update" | patch "$0" -; then
+            printf "Script has been updated\n"
+        else
+            die "Can't update for some reason!"
+        fi
+    fi
+    exit 0
+}
+
 get_skip_times() {
         lua_script="$HOME/.config/mpv/scripts/skip.lua"
         [ ! -f "$lua_script" ] && printf "\033[1;31m'skip.lua' script not found!\033[0m\n" 1>&2 && return 1
@@ -18,7 +38,9 @@ get_skip_times() {
         options="skip-start_time=$start_time,skip-end_time=$end_time"
         skip_flag="--script-opts=$options --script=$lua_script"
 }
-[ "$#" -ne 2 ] && printf "%s [\"title\"] [ep]\n" "${0##*/}" && exit 1
+
+[ "$#" -eq 1 ] && [ "$1" = "-U" ] && update_script
+[ "$#" -ne 2 ] && die "${0##*/} [\"title\"] [ep]"
 
 title="$1" ep_no="$2" get_skip_times
 printf "%s" "$skip_flag"
